/*
 * Created on 10. August 2005, 21:09
 * OWL-S Matchmaker
 * 
 * COPYRIGHT NOTICE
 * 
 * Copyright (C) 2005 DFKI GmbH, Germany
 * Developed by Benedikt Fries, Matthias Klusch
 * 
 * The code is free for non-commercial use only.
 * You can redistribute it and/or modify it under the terms
 * of the Mozilla Public License version 1.1  as
 * published by the Mozilla Foundation at
 * http://www.mozilla.org/MPL/MPL-1.1.txt
 */

package de.dfki.owlsmx.gui;
import de.dfki.owlsmx.gui.util.GUIState;
import de.dfki.owlsmx.gui.util.GUIUtils;

/**
 *
 * @author  Ben
 */
public class AboutDialog extends javax.swing.JPanel {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form AboutDialog */
    public AboutDialog() {
        initComponents();   
        GUIUtils.makeTransparent(jTextArea1);
        //GUIUtils.makeTransparent(jTextArea2);
    }    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel3 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setText("OWLS-MX Matchmaker 1.1");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jTextArea1.setBackground(new java.awt.Color(246, 246, 246));
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextArea1.setText("Developed by Benedikt Fries and Matthias Klusch at the \nGerman Research Center for Artificial Intelligence \n(DFKI Saarbruecken, Germany) \nin the project SCALLOPS (http://www.dfki.de/scallops)\n\nReleased under the Mozilla public licence MPL 1.1");
        add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 460, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText("http://owls-mx.projects.semwebcentral.org/");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource(GUIState.logoPath)));
        add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jTextArea2.setBackground(new java.awt.Color(246, 246, 246));
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 10));
        jTextArea2.setText("Copyright (C) 2005 DFKI\n \n   OWLS-MX is free for non-commercial use only.\n   You can redistribute it and/or modify it under the terms \n   of the Mozilla Public License version 1.1  as \n   published by the Mozilla Foundation at \n   http://www.mozilla.org/MPL/MPL-1.1.txt\n\nDISCLAIMER OF WARRANTY:\n\n    COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN \"AS IS\" BASIS, \n    WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, \n    WITHOUT LIMITATION, WARRANTIES THAT THE COVERED CODE IS FREE OF DEFECTS, \n    MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE OR NON-INFRINGING. THE \n    ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE COVERED CODE \n    IS WITH YOU. SHOULD ANY COVERED CODE PROVE DEFECTIVE IN ANY RESPECT, \n    YOU (NOT THE INITIAL DEVELOPER OR ANY OTHER CONTRIBUTOR) ASSUME THE \n    COST OF ANY NECESSARY SERVICING, REPAIR OR CORRECTION. THIS DISCLAIMER \n    OF WARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS LICENSE. NO USE OF ANY \n    COVERED CODE IS AUTHORIZED HEREUNDER EXCEPT UNDER THIS DISCLAIMER.");
        jScrollPane1.setViewportView(jTextArea2);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 460, 220));

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
    
}
